name: selectable_icon
description: A flutter package that will allow you to create a selectable icon with multiple customizations.
version: 1.0.3
homepage: https://github.com/mantreshkhurana/selectable_icon
repository: https://github.com/mantreshkhurana/selectable_icon

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true